# Generated by Django 3.2 on 2024-06-29 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_id', models.CharField(max_length=100, unique=True)),
                ('timestamp', models.DateTimeField()),
                ('log_type', models.CharField(max_length=50)),
                ('message', models.TextField()),
            ],
        ),
    ]
